const CREATE_TEMPLATE = "CREATE_TEMPLATE";
const READ_TEMPLATE = "READ_TEMPLATE";
const DELETE_TEMPLATE = "DELETE_TEMPLATE";

const CREATE_PATIENT = "CREATE_PATIENT";
const READ_PATIENT = "READ_PATIENT";
const DELETE_PATIENT = "DELETE_PATIENT";

const PERMISSIONS = {
  CREATE_TEMPLATE,
  READ_TEMPLATE,
  DELETE_TEMPLATE,
  CREATE_PATIENT,
  READ_PATIENT,
  DELETE_PATIENT,
};

export default PERMISSIONS;
